// Generated from CAR-LIGHTS 1.2.9 (ysn.com.app.lights) R.array/mode and
// R.array/circle (English). Do not edit by hand; see docs/carlights_findings.md.

/// CAR-LIGHTS pattern list. The wheel index `i` is sent as mode id `i + 1`
/// (`ModelFragment.onItemSelected`), so ids run 1–122 with 1 = auto cycle.
const List<({int id, String name})> carLightsModes = [
  (id: 1, name: 'Auto cycle color changing'),
  (id: 2, name: '1:Static red'),
  (id: 3, name: '2:Static green'),
  (id: 4, name: '3:Static blue'),
  (id: 5, name: '4:Static yellow'),
  (id: 6, name: '5:Static purple'),
  (id: 7, name: '6:Static cyan'),
  (id: 8, name: '7:Static white'),
  (id: 9, name: '8:Gradual transition jumping function'),
  (id: 10, name: '9:Red jumping mode'),
  (id: 11, name: '10:Green jumping mode'),
  (id: 12, name: '11:Blue jumping mode'),
  (id: 13, name: '12:Red jumping mode'),
  (id: 14, name: '13:Green jumping mode'),
  (id: 15, name: '14:Blue jumping mode'),
  (id: 16, name: '15:Yellow jumping mode'),
  (id: 17, name: '16:Cyan jumping mode'),
  (id: 18, name: '17:Purple jumping mode'),
  (id: 19, name: '18:White jumping mode'),
  (id: 20, name: '19:White based red jumping mode'),
  (id: 21, name: '20:Red based green jumping mode'),
  (id: 22, name: '21:Green based blue jumping mode'),
  (id: 23, name: '22:Blue based yellow jumping mode'),
  (id: 24, name: '23:Yellow based cyan jumping mode'),
  (id: 25, name: '24:Cyan based purple jumping mode'),
  (id: 26, name: '25:Purple based white jumping mode'),
  (id: 27, name: '26:Rotative gradient red blue colors'),
  (id: 28, name: '27:Rotative gradient red green colors'),
  (id: 29, name: '28:Rotative gradient red cyan colors'),
  (id: 30, name: '29:Rotative gradient red purple colors'),
  (id: 31, name: '30:Rotative gradient green yellow colors'),
  (id: 32, name: '31:Rotative gradient cyan green colors'),
  (id: 33, name: '32:Rotative gradient purple blue colors'),
  (id: 34, name: '33:Rotative gradient cyan blue colors'),
  (id: 35, name: '34:Rotative gradient red yellow colors'),
  (id: 36, name: '35:Rotative gradient purple red colors'),
  (id: 37, name: '36:Rotative gradient purple green colors'),
  (id: 38, name: '37:Rotative gradient red white colors'),
  (id: 39, name: '38:Rotative gradient green white colors'),
  (id: 40, name: '39:Forward red green blue rotative jumping mode'),
  (id: 41, name: '40:Backward red green blue rotative jumping mode'),
  (id: 42, name: '41:Forward rainbow seven color jumping mode'),
  (id: 43, name: '42:Backward rainbow seven color jumping mode'),
  (id: 44, name: '43:Curtain-up red green blue jumping mode'),
  (id: 45, name: '44:Curtain-up rainbow seven color jumping mode'),
  (id: 46, name: '45:Forward red green blue running mode'),
  (id: 47, name: '46:Backward red green blue running mode'),
  (id: 48, name: '47:Forward mixed red green blue running mode'),
  (id: 49, name: '48:Backward mixed red green blue running mode'),
  (id: 50, name: '49:Forward rainbow seven color chasing mode'),
  (id: 51, name: '50:Backward rainbow seven color chasing mode'),
  (id: 52, name: '51:Curtain-up red green blue mode'),
  (id: 53, name: '52:Curtain-up rainbow seven color mode'),
  (id: 54, name: '53:Flashing red green blue'),
  (id: 55, name: '54:Flashing rainbow seven color'),
  (id: 56, name: '55:Red green blue stroboflash mode'),
  (id: 57, name: '56:Mixed red green blue stroboflash mode'),
  (id: 58, name: '57:Rainbow seven color stroboflash mode'),
  (id: 59, name: '58:Green blue yellow overlap-jumping mode'),
  (id: 60, name: '59:Blue yellow cyan overlap-jumping mode'),
  (id: 61, name: '60:Yellow purple cyan overlap-jumping mode'),
  (id: 62, name: '61:Rainbow seven color running mode'),
  (id: 63, name: '62:Red green blue running mode'),
  (id: 64, name: '63:Mixed red green blue running mode'),
  (id: 65, name: '64:Red green running mode'),
  (id: 66, name: '65:Green blue running mode'),
  (id: 67, name: '66:Yellow cyan running mode'),
  (id: 68, name: '67:Cyan purple running mode'),
  (id: 69, name: '68:Black white running mode'),
  (id: 70, name: '69:Rotative gradient rainbow seven color'),
  (id: 71, name: '70:Rotative gradient red and green'),
  (id: 72, name: '71:Rotative gradient red and blue'),
  (id: 73, name: '72:Rotative gradient red and yellow'),
  (id: 74, name: '73:Rotative gradient red and cyan'),
  (id: 75, name: '74:Rotative gradient red and purple'),
  (id: 76, name: '75:Rotative gradient red and white'),
  (id: 77, name: '76:Rotative gradient green and blue'),
  (id: 78, name: '77:Rotative gradient green and yellow'),
  (id: 79, name: '78:Rotative gradient green and cyan'),
  (id: 80, name: '79:Rotative gradient green and purple'),
  (id: 81, name: '80:Rotative gradient green and white'),
  (id: 82, name: '81:Rotative gradient blue and yellow'),
  (id: 83, name: '82:Blue base green wheeling mode'),
  (id: 84, name: '83:Red base green wheeling mode'),
  (id: 85, name: '84:Cyan base green wheeling mode'),
  (id: 86, name: '85:Purple base green wheeling mode'),
  (id: 87, name: '86:Yellow base green wheeling mode'),
  (id: 88, name: '87:White base green wheeling mode'),
  (id: 89, name: '88:Red base blue wheeling mode'),
  (id: 90, name: '89:Cyan base blue wheeling mode'),
  (id: 91, name: '90:Purple base blue wheeling mode'),
  (id: 92, name: '91:Yellow base blue wheeling mode'),
  (id: 93, name: '92:White base blue wheeling mode'),
  (id: 94, name: '93:Cyan base red wheeling mode'),
  (id: 95, name: '94:Green dripping mode'),
  (id: 96, name: '95:Blue dripping mode'),
  (id: 97, name: '96:Red dripping mode'),
  (id: 98, name: '97:Cyan dripping mode'),
  (id: 99, name: '98:Purple dripping mode'),
  (id: 100, name: '99:Yellow dripping mode'),
  (id: 101, name: '100:White dripping mode'),
  (id: 102, name: '101:Green chasing mode'),
  (id: 103, name: '102:Blue chasing mode'),
  (id: 104, name: '103:Red chasing mode'),
  (id: 105, name: '104:Cyan chasing mode'),
  (id: 106, name: '105:Yellow chasing mode'),
  (id: 107, name: '106:White chasing mode'),
  (id: 108, name: '107:Bidirectional green chasing mode'),
  (id: 109, name: '108:Bidirectional blue chasing mode'),
  (id: 110, name: '109:Bidirectional red chasing mode'),
  (id: 111, name: '110:Bidirectional purple chasing mode'),
  (id: 112, name: '111:Bidirectional yellow chasing mode'),
  (id: 113, name: '112:Bidirectional white chasing mode'),
  (id: 114, name: '113:Bidirectional cyan chasing mode'),
  (id: 115, name: '114:Purple base bidirectional green chasing mode'),
  (id: 116, name: '115:Cyan base bidirectional red chasing mode'),
  (id: 117, name: '116:Green wheeling mode'),
  (id: 118, name: '117:Blue wheeling mode'),
  (id: 119, name: '118:Red wheeling mode'),
  (id: 120, name: '119:Purple wheeling mode'),
  (id: 121, name: '120:Yellow wheeling mode'),
  (id: 122, name: '121:White wheeling mode'),
];

/// Chip-setting ring sizes (`R.array/circle`). Wheel index `i` is sent as
/// `i + 1` for both the big and the small ring (`ChipActivity.onItemSelected`).
const List<({int id, String name})> carLightsChipSizes = [
  (id: 1, name: 'SMT66'),
  (id: 2, name: 'SMT60'),
  (id: 3, name: 'SMT54'),
  (id: 4, name: 'SMT50'),
  (id: 5, name: 'SMT48'),
  (id: 6, name: 'SMT45'),
  (id: 7, name: 'SMT39'),
  (id: 8, name: 'SMT36'),
  (id: 9, name: 'SMT33'),
  (id: 10, name: 'SMT30'),
  (id: 11, name: 'SMT24'),
];
