// Generated from LED+LAMP 4.3.5 R.array/dmx_model (English).
/// LEDCAR-02 / LEDDMX animation modes, from LED+LAMP 4.3.5
/// `R.array/dmx_model` (English). 211 entries; AUTO (255) first.
const List<({int id, String name})> ledCar02Modes = [
  (id: 255, name: 'AUTO'),
  (id: 1, name: 'Forward Dreaming'),
  (id: 2, name: 'Backward Dreaming'),
  (id: 3, name: 'Forward 7 Colors'),
  (id: 4, name: 'Backward 7 Colors'),
  (id: 5, name: 'Forward RD/GN/BU'),
  (id: 6, name: 'Backward RD/GN/BU'),
  (id: 7, name: 'Forward YE/CN/VT'),
  (id: 8, name: 'Backward YE/CN/VT'),
  (id: 9, name: 'Forward 6 Colors RD'),
  (id: 10, name: 'Backward 6 Colors RD'),
  (id: 11, name: 'Forward 6 Colors GN'),
  (id: 12, name: 'Backward 6 Colors GN'),
  (id: 13, name: 'Forward 6 Colors BU'),
  (id: 14, name: 'Backward 6 Colors BU'),
  (id: 15, name: 'Forward 6 Colors CN'),
  (id: 16, name: 'Backward 6 Colors CN'),
  (id: 17, name: 'Forward 6 Colors YE'),
  (id: 18, name: 'Backward 6 Colors YE'),
  (id: 19, name: 'Forward 6 Colors VT'),
  (id: 20, name: 'Backward 6 Colors VT'),
  (id: 21, name: 'Forward 6 Colors WH'),
  (id: 22, name: 'Backward 6 Colors WH'),
  (id: 23, name: 'Forward Trailing 7 Colors'),
  (id: 24, name: 'Backward Trailing 7 Colors'),
  (id: 25, name: 'Forward Trailing RD'),
  (id: 26, name: 'Backward Trailing RD'),
  (id: 27, name: 'Forward Trailing GN'),
  (id: 28, name: 'Backward Trailing GN'),
  (id: 29, name: 'Forward Trailing BU'),
  (id: 30, name: 'Backward Trailing BU'),
  (id: 31, name: 'Forward Trailing YE'),
  (id: 32, name: 'Backward Trailing YE'),
  (id: 33, name: 'Forward Trailing CN'),
  (id: 34, name: 'Backward Trailing CN'),
  (id: 35, name: 'Forward Trailing VT'),
  (id: 36, name: 'Backward Trailing VT'),
  (id: 37, name: 'Forward Trailing WH'),
  (id: 38, name: 'Backward Trailing WH'),
  (id: 39, name: 'Forward Streaming 7 Colors'),
  (id: 40, name: 'Backward Streaming 7 Colors'),
  (id: 41, name: 'Forward Streaming RD/GN/BU'),
  (id: 42, name: 'Backward Streaming RD/GN/BU'),
  (id: 43, name: 'Forward Streaming YE/CN/VT'),
  (id: 44, name: 'Backward Streaming YE/CN/VT'),
  (id: 45, name: 'Forward Streaming RD/GN'),
  (id: 46, name: 'Backward Streaming RD/GN'),
  (id: 47, name: 'Forward Streaming GN/BU'),
  (id: 48, name: 'Backward Streaming GN/BU'),
  (id: 49, name: 'Forward Streaming YE/BU'),
  (id: 50, name: 'Backward Streaming YE/BU'),
  (id: 51, name: 'Forward Streaming YE/CN'),
  (id: 52, name: 'Backward Streaming YE/CN'),
  (id: 53, name: 'Forward Streaming CN/VT'),
  (id: 54, name: 'Backward Streaming CN/VT'),
  (id: 55, name: 'Forward Streaming BK/WH'),
  (id: 56, name: 'Backward Streaming BK/WH'),
  (id: 57, name: 'Open Curtain 7 Colors'),
  (id: 58, name: 'Close Curtain 7 Colors'),
  (id: 59, name: 'Open Curtain RD/GN/BU'),
  (id: 60, name: 'Close Curtain RD/GN/BU'),
  (id: 61, name: 'Open Curtain YE/CN/VT'),
  (id: 62, name: 'Close Curtain YE/CN/VT'),
  (id: 63, name: 'Forward Follow Spot 7 Colors'),
  (id: 64, name: 'Backward Follow Spot 7 Colors'),
  (id: 65, name: 'Forward Follow Spot RD/GN/BU'),
  (id: 66, name: 'Backward Follow Spot RD/GN/BU'),
  (id: 67, name: 'Forward Follow Spot YE/CN/VT'),
  (id: 68, name: 'Backward Follow Spot YE/CN/VT'),
  (id: 69, name: 'Forward Flutter 7 Colors'),
  (id: 70, name: 'Backward Flutter 7 Colors'),
  (id: 71, name: 'Forward Flutter RD/GN/BU'),
  (id: 72, name: 'Backward Flutter RD/GN/BU'),
  (id: 73, name: 'Forward Flutter YE/CN/VT'),
  (id: 74, name: 'Backward Flutter YE/CN/VT'),
  (id: 75, name: 'Hop 7 Colors'),
  (id: 76, name: 'Hop RD/GN/BU'),
  (id: 77, name: 'Hop RD/GN/BU'),
  (id: 78, name: 'Strobe 7 Colors'),
  (id: 79, name: 'Strobe RD/GN/BU'),
  (id: 80, name: 'Strobe YE/CN/VT'),
  (id: 81, name: 'Gradual 7 Colors'),
  (id: 82, name: 'Gradual RD/E'),
  (id: 83, name: 'Gradual RD/VT'),
  (id: 84, name: 'Gradual GN/CN'),
  (id: 85, name: 'Gradual GN/YE'),
  (id: 86, name: 'Gradual BU/VT'),
  (id: 87, name: 'Close Curtain RD'),
  (id: 88, name: 'Close Curtain GN'),
  (id: 89, name: 'Close Curtain BU'),
  (id: 90, name: 'Close Curtain YE'),
  (id: 91, name: 'Close Curtain CN'),
  (id: 92, name: 'Close Curtain VT'),
  (id: 93, name: 'Close Curtain WH'),
  (id: 94, name: 'Open Curtain RD'),
  (id: 95, name: 'Open Curtain GN'),
  (id: 96, name: 'Open Curtain BU'),
  (id: 97, name: 'Open Curtain YE'),
  (id: 98, name: 'Open Curtain CN'),
  (id: 99, name: 'Open Curtain VT'),
  (id: 100, name: 'Open Curtain WH'),
  (id: 101, name: 'Horse Race RD'),
  (id: 102, name: 'Horse Race GN'),
  (id: 103, name: 'Horse Race BU'),
  (id: 104, name: 'Horse Race YE'),
  (id: 105, name: 'Horse Race CN'),
  (id: 106, name: 'Horse Race VT'),
  (id: 107, name: 'Horse Race WH'),
  (id: 108, name: 'Forward Run RD'),
  (id: 109, name: 'Backward Run RD'),
  (id: 110, name: 'Forward Run GN'),
  (id: 111, name: 'Backward Run GN'),
  (id: 112, name: 'Forward Run BU'),
  (id: 113, name: 'Backward Run BU'),
  (id: 114, name: 'Forward Run YE'),
  (id: 115, name: 'Backward Run YE'),
  (id: 116, name: 'Forward Run CN'),
  (id: 117, name: 'Backward Run CN'),
  (id: 118, name: 'Forward Run VT'),
  (id: 119, name: 'Backward Run VT'),
  (id: 120, name: 'Forward Run WH'),
  (id: 121, name: 'Backward Run WH'),
  (id: 122, name: 'Forward Run 7 Colors'),
  (id: 123, name: 'Backward Run 7 Colors'),
  (id: 124, name: 'Forward Run RD/GN/BU'),
  (id: 125, name: 'Backward Run RD/GN/BU'),
  (id: 126, name: 'Forward Run YE/CN/VT'),
  (id: 127, name: 'Backward Run YE/CN/VT'),
  (id: 128, name: 'Forward Run BU/YE/VT'),
  (id: 129, name: 'Forward Run GN/BU/YE'),
  (id: 130, name: 'Backward Run BU/YE/VT'),
  (id: 131, name: 'Forward Run RD/ON/WH'),
  (id: 132, name: 'Backward Run RD/ON/WH'),
  (id: 133, name: 'Forward Run GN ON RD'),
  (id: 134, name: 'Backward Run GN ON RD'),
  (id: 135, name: 'Forward Run BU ON GN'),
  (id: 136, name: 'Backward Run BU ON GN'),
  (id: 137, name: 'Forward Run YE ON BU'),
  (id: 138, name: 'Backward Run YE ON BU'),
  (id: 139, name: 'Forward Run CN ON YE'),
  (id: 140, name: 'Backward Run CN ON YE'),
  (id: 141, name: 'Forward Run VT ON CN'),
  (id: 142, name: 'Backward Run VT ON CN'),
  (id: 143, name: 'Forward Run WH ON VT'),
  (id: 144, name: 'Backward Run WH ON VT'),
  (id: 145, name: 'Forward Run WH ON RD'),
  (id: 146, name: 'Backward Run WH ON RD'),
  (id: 147, name: 'Forward Run 7 COLOR ON RD'),
  (id: 148, name: 'Backward Run 7 COLOR ON RD'),
  (id: 149, name: 'Forward Run 7 COLOR ON GN'),
  (id: 150, name: 'Backward Run 7 COLOR ON GN'),
  (id: 151, name: 'Forward Run 7 COLOR ON BU'),
  (id: 152, name: 'Backward Run 7 COLOR ON BU'),
  (id: 153, name: 'Forward Run 7 COLOR ON YE'),
  (id: 154, name: 'Backward Run 7 COLOR ON YE'),
  (id: 155, name: 'Forward Run 7 COLOR ON CN'),
  (id: 156, name: 'Backward Run 7 COLOR ON CN'),
  (id: 157, name: 'Forward Run 7 COLOR ON VT'),
  (id: 158, name: 'Backward Run 7 COLOR ON VT'),
  (id: 159, name: 'Forward Run 7 COLOR ON WH'),
  (id: 160, name: 'Backward Run 7 COLOR ON WH'),
  (id: 161, name: 'Forward Flow WH RD WH'),
  (id: 162, name: 'Backward Flow WH RD WH'),
  (id: 163, name: 'Forward Flow WH GN WH'),
  (id: 164, name: 'Backward Flow WH GN WH'),
  (id: 165, name: 'Forward Flow WH BU WH'),
  (id: 166, name: 'Backward Flow WH BU WH'),
  (id: 167, name: 'Forward Flow WH YE WH'),
  (id: 168, name: 'Backward Flow WH YE WH'),
  (id: 169, name: 'Forward Flow WH CN WH'),
  (id: 170, name: 'Backward Flow WH CN WH'),
  (id: 171, name: 'Forward Flow WH VT WH'),
  (id: 172, name: 'Backward Flow WH VT WH'),
  (id: 173, name: 'Forward Flow RD WH RD'),
  (id: 174, name: 'Backward Flow RD WH RD'),
  (id: 175, name: 'Forward Flow GN WH GN'),
  (id: 176, name: 'Backward Flow GN WH GN'),
  (id: 177, name: 'Forward Flow BU WH BU'),
  (id: 178, name: 'Backward Flow BU WH BU'),
  (id: 179, name: 'Forward Flow YE WH YE'),
  (id: 180, name: 'Backward Flow YE WH YE'),
  (id: 181, name: 'Forward Flow CN WH CN'),
  (id: 182, name: 'Backward Flow CN WH CN'),
  (id: 183, name: 'Forward Flow VT WH VT'),
  (id: 184, name: 'Backward Flow VT WH VT'),
  (id: 185, name: 'Forward Run GN ON BU'),
  (id: 186, name: 'Backward Run GN ON BU'),
  (id: 187, name: 'Forward Run GN ON RD'),
  (id: 188, name: 'Backward Run GN ON RD'),
  (id: 189, name: 'Forward Run RD ON BU'),
  (id: 190, name: 'Backward Run RD ON BU'),
  (id: 191, name: 'Forward Run CN ON YE'),
  (id: 192, name: 'Backward Run CN ON YE'),
  (id: 193, name: 'Forward Run YE ON VT'),
  (id: 194, name: 'Backward Run YE ON VT'),
  (id: 195, name: 'Forward Run WH ON YE'),
  (id: 196, name: 'Backward Run WH ON YE'),
  (id: 197, name: 'Forward Run YE ON WH'),
  (id: 198, name: 'Backward Run YE ON WH'),
  (id: 199, name: 'Forward Swab 7 COLORS'),
  (id: 200, name: 'Backward Swab 7 COLORS'),
  (id: 201, name: 'Forward Swab RD GN BU'),
  (id: 202, name: 'Backward Swab RD GN BU'),
  (id: 203, name: 'Forward Swab YE CN VT'),
  (id: 204, name: 'Backward Swab YE CN VT'),
  (id: 205, name: 'Open Curtain Swab 7 COLORS'),
  (id: 206, name: 'Close Curtain Swab 7 COLORS'),
  (id: 207, name: 'Open Curtain Swab R G B'),
  (id: 208, name: 'Close Curtain Swab R G B'),
  (id: 209, name: 'Open Curtain Swab Y C P'),
  (id: 210, name: 'Close Curtain Swab Y C P'),
];
